name: secp256r1
description: >
  A Flutter plugin that support secp256r1 by Secure Enclave on iOS.
version: 1.0.0
repository: https://github.com/FranzZehetleitner/flutter_secp256r1

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cryptography: ^2.7.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SecureP256Plugin
